--type nvim-lint.options
-- local options = {}
-- -- require("nvim-lint").setup(options)
-- require("nvim-lint").setup(options)
-- local linter = require("lint")
-- linter.linters_by_ft = {
-- 	javascript = { "eslint_d" },
-- 	typescript = { "eslint_d" },
-- 	python = { "pylint" },
-- }
--
-- require("mason-tool-installer").setup({
-- 	-- ensure_installed = { "pylint" },
-- })
