#custom_cursor_colors = true
live_config_reload = true

[bell]
animation = "EaseOutExpo"
color = "0xffffff"
duration = 0

[cursor]
style = "Block"
unfocused_hollow = true

[debug]
log_level = "OFF"
persistent_logging = false
print_events = false
render_timer = false

[font]
size = 12.0
#use_thin_strokes = true

[font.bold]
family = "Iosevka"
style = "Medium"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Iosevka"
style = "Light Italic"

[font.normal]
family = "Iosevka"
style = "Light"

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = false

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

#[mouse.double_click]
#threshold = 300
#
#[mouse.triple_click]
#threshold = 300

[scrolling]
history = 0
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
decorations = "Full"
#decoration_theme_variant = "Dark"
dynamic_padding = false
opacity = 0.8
startup_mode = "Windowed"

[window.dimensions]
columns = 100
lines = 85

[window.padding]
x = 2
y = 2

# Colors (Gruvbox dark)
[colors]
  # Default colors
[colors.primary]
    # hard contrast: background = '#1d2021'
    background= '#282828'
    # soft contrast: background = '#32302f'
    foreground= '#ebdbb2'

  # Normal colors
[colors.normal]
    black=   '#282828'
    red=     '#cc241d'
    green=   '#98971a'
    yellow=  '#d79921'
    blue=    '#458588'
    magenta= '#b16286'
    cyan=    '#689d6a'
    white=   '#a89984'

  # Bright colors
[colors.bright]
    black=   '#928374'
    red=     '#fb4934'
    green=   '#b8bb26'
    yellow=  '#fabd2f'
    blue=    '#83a598'
    magenta= '#d3869b'
    cyan=    '#8ec07c'
    white=   '#ebdbb2'
